TFM/TFM/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('YoPuedo.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "YoPuedo.views.page_not_found"

TFM/YoPuedo/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name="index"),
    path('registrarse/', views.registrarse, name="registrarse"),
    path('validar_clave/<str:tipo>/<str:email>', views.validar_clave,
         name="validar_clave"),
    path('iniciar_sesion/', views.iniciar_sesion, name="iniciar_sesion"),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='YoPuedo/recuperacion_contrasena/recuperacion_contrasena.html',
        html_email_template_name='YoPuedo/envio_correos/envio_recuperar_contrasena.html',
    ), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='YoPuedo/recuperacion_contrasena/recuperacion_contrasena_enviado.html'
    ), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='YoPuedo/recuperacion_contrasena/nueva_contrasena.html',
    ), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='YoPuedo/recuperacion_contrasena/recuperacion_done.html',
    ), name="password_reset_complete"),
    path('mis_retos/', views.mis_retos, name="mis_retos"),
    path('retos', views.get_retos, name="retos"),
    path('reto/<str:id_reto>', views.get_reto, name="reto"),
    path('nuevo_reto/', views.nuevo_reto, name="nuevo_reto"),
    path('iniciar_reto/<str:id_reto>', views.iniciar_reto, name="iniciar_reto"),
    path('editar_reto/<str:id_reto>', views.editar_reto, name="editar_reto"),
    path('eliminar_reto/<str:id_reto>', views.eliminar_reto, name="eliminar_reto"),
    path('coordinador_reto/<str:id_reto>', views.coordinador_reto,
         name="coordinador_reto"),
    path('animador_reto/<str:id_reto>', views.animador_reto, name="animador_reto"),
    path('amigos/', views.get_amigos, name="amigos"),
    path('calificar/<str:id_etapa>', views.calificar_etapa, name="calificar"),
    path('prueba/<str:id_etapa>', views.pruebas, name="pruebas"),
    path('animos/<str:id_etapa>', views.animos, name='animos'),
    path('mi_perfil/', views.mi_perfil, name='mi_perfil'),
    path('cerrar_sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path('eliminar/', views.eliminar, name='eliminar'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    path('mis_amigos/', views.mis_amigos, name='mis_amigos'),
    path('nuevos_amigos/', views.nuevos_amigos, name="nuevos_amigos"),
    path('eliminar_amigo/<str:amigo>', views.dejar_seguir, name="dejar_amigo"),
    path('perfil/<str:amigo>', views.ver_perfil, name="perfil"),
    path('notificaciones', views.get_notificaciones, name="notificaciones"),
    path('notificacion/<int:id_notificacion>', views.get_notificacion,
         name="notificacion"),
    path('solicitud_amistad/<str:usuario>', views.solicitud_amistad, name="solicitud"),
    path('rechazar/<str:usuario>', views.rechazar_amistad, name="rechazar"),
    path('contador_notificaciones/', views.contador_notificaciones,
         name='contador_notificaciones')
]

TFM/YoPuedo/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models
from django.utils import timezone


class UsuarioManager(BaseUserManager):
    def create_user(self, email, nombre, password, foto_perfil, clave_fija,
                    clave_aleatoria):
        usuario = self.model(email=email, nombre=nombre, password=password,
                             foto_perfil=foto_perfil, clave_fija=clave_fija,
                             clave_aleatoria=clave_aleatoria)
        usuario.set_password(password)
        usuario.is_superuser = False
        usuario.save(using=self._db)
        return usuario

    def get_by_natural_key(self, username):
        return self.get(email=username)


# TABLA YoPuedo_usuario
class Usuario(AbstractBaseUser):
    email = models.EmailField(primary_key=True)
    nombre = models.CharField(max_length=100)
    foto_perfil = models.CharField(max_length=200)
    clave_fija = models.CharField(max_length=16)
    clave_aleatoria = models.CharField(max_length=10)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nombre', 'password', 'foto_perfil', 'clave_fija',
                       'clave_aleatoria']

    objects = UsuarioManager()

    def get_username(self):
        return self.email

    def natural_key(self):
        return self.email

    def update_clave(self, clave):
        self.clave_aleatoria = clave
        self.save()


# TABLA YoPuedo_amistad
class Amistad(models.Model):
    amigo = models.ManyToManyField(Usuario, related_name="amigo")
    otro_amigo = models.ManyToManyField(Usuario, related_name="otro_amigo")


# TABLA YoPuedo_reto
class Reto(models.Model):
    id_reto = models.CharField(max_length=50, primary_key=True)
    titulo = models.CharField(max_length=500)
    objetivo = models.CharField(max_length=500)
    recompensa = models.CharField(max_length=500)
    estado = models.CharField(max_length=10, default="Propuesto")
    categoria = models.CharField(max_length=15)
    coordinador = models.ForeignKey(Usuario, on_delete=models.CASCADE)


# TABLA YoPuedo_participante:
class Participante(models.Model):
    usuario = models.ManyToManyField(Usuario)
    reto = models.ManyToManyField(Reto)


# TABLA YoPuedo_animador:
class Animador(models.Model):
    usuario = models.ManyToManyField(Usuario)
    reto = models.ManyToManyField(Reto)
    superanimador = models.BooleanField(default=False)


# TABLA YoPuedo_etapa
class Etapa(models.Model):
    id_etapa = models.CharField(max_length=50, primary_key=True)
    reto = models.ForeignKey(Reto, on_delete=models.CASCADE)
    objetivo = models.CharField(max_length=500)
    estado = models.CharField(max_length=10, default="Propuesto")


# TABLA YoPuedo_animo
class Animo(models.Model):
    etapa = models.ManyToManyField(Etapa)
    animador = models.ManyToManyField(Animador)
    mensaje = models.CharField(max_length=500)


# TABLA YoPuedo_prueba
class Prueba(models.Model):
    etapa = models.ManyToManyField(Etapa)
    participante = models.ManyToManyField(Participante)
    prueba = models.CharField(max_length=500)


# TABLA YoPuedo_calificacion
class Calificacion(models.Model):
    etapa = models.ManyToManyField(Etapa)
    participante = models.ManyToManyField(Participante)
    calificacion = models.CharField(max_length=500)


# TABLA YoPuedo_notificacion:
class Notificacion(models.Model):
    id_notificacion = models.BigAutoField(primary_key=True)
    mensaje = models.CharField(max_length=500)
    categoria = models.CharField(max_length=15) # Reto, Ánimo, Amistad
    estado = models.CharField(max_length=10, default="Recibido") # Recibido, Leído
    enlace = models.CharField(max_length=250)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)

TFM/YoPuedo/forms.py
import logging
import re

from django import forms
from django.forms import BaseFormSet

from .models import Usuario

from .utils import Utils

logger = logging.getLogger(__name__)


##########################################################################################

# Formulario de registro
class RegistroForm(forms.Form):
    email = forms.EmailField(label='Email:',
                             widget=forms.EmailInput(
                                 attrs={
                                     'class': 'form-control',
                                     'placeholder': 'ejemplo@ejemplo.com',
                                 }))
    nombre = forms.CharField(label='Nombre:', max_length='100',
                             widget=forms.TextInput(
                                 attrs={
                                     'class': 'form-control',
                                     'placeholder': 'María Jesús López'
                                 }))
    password = forms.CharField(label='Contraseña:',
                               widget=forms.PasswordInput(
                                   attrs={
                                       'class': 'form-control'
                                   }))
    password_again = forms.CharField(label='Repetir contraseña:',
                                     widget=forms.PasswordInput(
                                         attrs={
                                             'class': 'form-control col-10'
                                         }))
    foto_de_perfil = forms.ImageField(label='Foto de perfil:',
                                      widget=forms.ClearableFileInput(
                                          attrs={
                                              'class': 'form-control'
                                          }))

    def clean(self):
        logger.info("Checkeando registro")

        cleaned_data = super().clean()

        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password_again')

        if len(password) < 8:
            logger.error("La contraseña no tiene 8 caracteres como mínimo")
            self.add_error("password", "La contraseña debe tener entre 8 y 16 caracteres")

        if len(password) > 16:
            logger.error("La contraseña tiene más de 16 caracteres")
            self.add_error("password", "La contraseña debe tener entre 8 y 16 caracteres")

        if password != password2:
            logger.error("Las contraseñas introducidas no son iguales")
            self.add_error('password_again', "Las contraseñas deben ser iguales")

        if not re.findall('\d', password):
            logger.error("La contraseña no contiene números")
            self.add_error('password', "La contraseña debe contener al menos un número")

        if not re.findall('[A-Z]', password):
            logger.error("La contraseña no tiene ninguna mayúscula")
            self.add_error('password', "La contraseña debe tener al menos una mayúscula")

        if not re.findall('[a-z]', password):
            logger.error("La contraseña no tiene ninguna minúscula")
            self.add_error('password', "La contraseña debe contener al menos una letra "
                                       "en minúscula")

        if not re.findall('[()\[\]{}|\\`~!@#$%^&\*_\-\+=;:\'",<>./\?]', password):
            logger.error("La contraseña no contiene ningún símbolo")
            self.add_error('password', "La contraseña debe tener al menos uno de estos "
                                       "símbolos: "
                                       "()[]{}|\`~!@#$%^&*_-+=;:'\",<>./?")

        email = cleaned_data.get('email')

        if Usuario.objects.filter(email=email).exists():
            logger.error("Ya existe un usuario con ese email")
            self.add_error('email', "Ya existe una cuenta con ese email. Pruebe con "
                                    "otro.")

        return self


##########################################################################################

# Formulario de inicio sesión
class InicioForm(forms.Form):
    email_sesion = forms.EmailField(label='Email:',
                                    widget=forms.EmailInput(
                                        attrs={
                                            'class': 'form-control',
                                            'placeholder': 'ejemplo@ejemplo.com',
                                        }))
    password_sesion = forms.CharField(label='Contraseña:',
                                      widget=forms.PasswordInput(
                                          attrs={
                                              'class': 'form-control'
                                          }))

    def clean(self):
        logger.info("Checkeando inicio")

        cleaned_data = super().clean()

        email = cleaned_data.get('email_sesion')

        if not Usuario.objects.filter(email=email).exists():
            logger.error("No existe un usuario con ese email")
            self.add_error('password_sesion', "Usuario y/o contraseña incorrect@")

        else:
            password = cleaned_data.get('password_sesion')
            usuario = Usuario.objects.get(email=email)
            if not usuario.check_password(password):
                logger.error("Contraseña incorrecta")
                self.add_error('password_sesion', "Usuario y/o contraseña incorrect@")

        return self


##########################################################################################

# Formulario de petición de claves
class ClaveForm(forms.Form):
    email = forms.EmailField(widget=forms.HiddenInput())
    contador = forms.IntegerField(widget=forms.HiddenInput())
    clave = forms.CharField(label='Código de verificación:', max_length='16',
                            min_length='10', widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }))

    def clean(self):
        logger.info("Checkeando petición clave")

        cleaned_data = super().clean()

        email = cleaned_data.get('email')
        usuario = Usuario.objects.get(email=email)

        clave = cleaned_data.get('clave')

        if usuario.clave_fija != clave and usuario.clave_aleatoria != clave:
            logger.error("Las claves no coinciden con la introducida")
            self.add_error('clave', 'La clave introducida es incorrecta. Por favor, '
                                    'introdúcela de nuevo.')

        return self


##########################################################################################

# Formulario de reto GENERAL
class RetoGeneralForm(forms.Form):
    titulo = forms.CharField(label='Título: ', max_length='500',
                             widget=forms.TextInput(
                                 attrs={
                                     'class': 'form-control'
                                 }), required=False)
    objetivo_imagen = forms.ImageField(label="Subir foto",
                                       widget=forms.ClearableFileInput(
                                           attrs={
                                               'class': 'd-none input-media'
                                           }),
                                       required=False)
    objetivo_audio = forms.FileField(label="Subir audio",
                                     widget=forms.ClearableFileInput(
                                         attrs={
                                             'class': 'd-none input-media',
                                             'accept': "audio/*"
                                         }),
                                     required=False)
    objetivo_video = forms.FileField(label="Subir vídeo",
                                     widget=forms.ClearableFileInput(
                                         attrs={
                                             'class': 'd-none input-media',
                                             'accept': "video/*"
                                         }),
                                     required=False)

    objetivo_texto = forms.CharField(max_length='500', widget=forms.Textarea(
        attrs={
            'class': 'form-control mt-2 mb-2',
            'placeholder': 'O escribe el objetivo ...',
            'rows': '2'
        }), required=False)

    categoria = forms.ChoiceField(label="Categoría: ", choices=Utils.CATEGORIAS_CHOOSE,
                                  widget=forms.Select(
                                      attrs={
                                          'class': 'col'
                                      }), required=False)

    recompensa_imagen = forms.ImageField(label="Subir foto",
                                         widget=forms.ClearableFileInput(
                                             attrs={
                                                 'class': 'd-none input-media'
                                             }),
                                         required=False)
    recompensa_audio = forms.FileField(label="Subir audio",
                                       widget=forms.ClearableFileInput(
                                           attrs={
                                               'class': 'd-none input-media',
                                               'accept': "audio/*"
                                           }),
                                       required=False)
    recompensa_video = forms.FileField(label="Subir vídeo",
                                       widget=forms.ClearableFileInput(
                                           attrs={
                                               'class': 'd-none input-media',
                                               'accept': "video/*"
                                           }),
                                       required=False)

TFM/templates/YoPuedo/formulario_reto/etapa.html
{% load get_value %}
<div class='form-group fw-bold {% if etapa_form.objetivo_texto.errors %} errorlist {% endif %}'>
  {{ etapa_form.id_etapa }}
  <i class="fa-solid fa-flag-checkered"></i>
  Objetivo:
  <div class="objetivo botones row m-1 justify-content-between">
    <div class="col-3 p-0 d-flex justify-content-center">
      <button class="uploadfile imagen btn btn-primary fw-bold" type="button">
        <label for="{{ etapa_form.objetivo_imagen.id_for_label }}">
          <i class="fa-solid fa-image"></i>
          <span class="label d-none d-sm-inline">
            {% with id=etapa_form.id_etapa.value %}
              {% if id in etapas_objetivo.keys %}
                {% with dato=etapas_objetivo|get_item:id|get_item:"objetivo_imagen" %}
                {% if dato != "" %}
                  {{ dato }}
                {% else %}
                  {{ etapa_form.objetivo_imagen.label }}
                {% endif %}
                {% endwith %}
              {% else %}
                {{ etapa_form.objetivo_imagen.label }}
              {% endif %}
            {% endwith %}
          </span>
        </label>
        {{ etapa_form.objetivo_imagen }}
      </button>
    </div>

    <div class="col-3 p-0 d-flex justify-content-center">
      <button class="uploadfile uploadaudio btn btn-primary fw-bold" type="button">
        <label for="{{ etapa_form.objetivo_audio.id_for_label }}">
          <i class="fa-solid fa-headphones"></i>
          <span class="label d-none d-sm-inline">
            {% with id=etapa_form.id_etapa.value %}
              {% if id in etapas_objetivo.keys %}
                {% with dato=etapas_objetivo|get_item:id|get_item:"objetivo_audio" %}
                {% if dato != "" %}
                  {{ dato }}
                {% else %}
                  {{ etapa_form.objetivo_audio.label }}
                {% endif %}
                {% endwith %}
              {% else %}
                {{ etapa_form.objetivo_audio.label }}
              {% endif %}
            {% endwith %}
          </span>
        </label>
        {{ etapa_form.objetivo_audio }}
      </button>
    </div>

    <div class="col-3 p-0 d-flex justify-content-center">
      <button class="uploadfile video btn btn-primary fw-bold" type="button">
        <label for="{{ etapa_form.objetivo_video.id_for_label }}">
          <i class="fa-solid fa-video"></i>
          <span class="label d-none d-sm-inline">
            {% with id=etapa_form.id_etapa.value %}
              {% if id in etapas_objetivo.keys %}
                {% with dato=etapas_objetivo|get_item:id|get_item:"objetivo_video" %}
                {% if dato != "" %}
                  {{ dato }}
                {% else %}
                  {{ etapa_form.objetivo_video.label }}
                {% endif %}
                {% endwith %}
              {% else %}
                {{ etapa_form.objetivo_video.label }}
              {% endif %}
            {% endwith %}
          </span>
        </label>
        {{ etapa_form.objetivo_video }}
      </button>
    </div>
  </div>

  <div class="row align-items-center">
    <div class="col-9 col-sm-10 col-lg-11 {{ etapa_form.objetivo_texto.name }}">
      {{ etapa_form.objetivo_texto }}
    </div>
    <div class="col-2 col-lg-1">
      {% include 'YoPuedo/elementos/microfono.html' with elementRecognition=etapa_form.objetivo_texto.id_for_label %}
    </div>
  </div>

  {% for error in etapa_form.objetivo_texto.errors%}
  <div class="errorlist">
    <i class="bi bi-x-circle-fill"></i>
    {{ error }}
  </div>
  {% endfor %}

  <div class="row botones-etapa">
    {% if num_etapa != 1 %}
    <div class='form-group d-flex justify-content-start mt-2 mt-sm-3 mt-lg-5 col'>
        <button id="boton-anterior-etapa" class="btn btn-primary fw-bold anterior"
                type="button"
                onclick="cambiarPestanaEtapa(getNumEtapa({{num_etapa}}, -1), 'form-etapa-content')">
            <i class="fa-solid fa-angle-left"></i>
            Anterior etapa
        </button>
    </div>

    <div class='form-group d-flex justify-content-center mt-2 mt-sm-3 mt-lg-5 col'>
        <button id="boton-borrar-etapa" class="btn btn-primary fw-bold borrar"
                type="button"
                onclick="borrarEtapa({{num_etapa}})">
            <i class="fa-sharp fa-solid fa-trash"></i>
            Borrar etapa
        </button>
    </div>
    {% endif %}

    {% if max_etapas != etapas_form.total_form_count or num_etapa != etapas_form.total_form_count %}
    <div class='form-group d-flex justify-content-end mt-2 mt-sm-3 mt-lg-5 col'>
        <button
                id="{% if etapas_form.total_form_count == num_etapa %}boton-nueva-etapa{% else %}boton-siguiente-etapa{% endif %}"
                class="btn btn-primary fw-bold {% if etapas_form.total_form_count == num_etapa %}nueva{% else %}siguiente{% endif %}"
                type="button"
                onclick="cambiarPestanaEtapa(getNumEtapa({{num_etapa}}, 1), 'form-etapa-content')">
          {% if etapas_form.total_form_count == num_etapa %}
            <i class="fa-solid fa-plus"></i>
            Nueva etapa
          {% else %}
            Siguiente etapa
            <i class="fa-solid fa-angle-right"></i>
          {% endif %}
        </button>
    </div>
    {% endif %}
  </div>
</div>

TFM/templates/YoPuedo/formulario_reto/general.html
<div class='form-group fw-bold {% if general_form.titulo.errors %} errorlist {% endif %}'>
    <i class="fa-solid fa-bullseye"></i>
    {{ general_form.titulo.label }}
    <div class="row align-items-center">
        <div class="col-9 col-sm-10 col-lg-11 {{ general_form.titulo.name }}">
            {{ general_form.titulo }}
        </div>
        <div class="col-2 col-lg-1 d-flex justify-content-center">
            {% include 'YoPuedo/elementos/microfono.html' with elementRecognition=general_form.titulo.id_for_label %}
        </div>
    </div>

    {% for error in general_form.titulo.errors %}
    <div class="errorlist">
      <i class="bi bi-x-circle-fill"></i>
      {{ error }}
    </div>
    {% endfor %}
</div>

<div class='form-group fw-bold {% if general_form.objetivo_texto.errors %} errorlist {% endif %} mt-4'>
    <i class="fa-solid fa-flag-checkered"></i>
    Objetivo:
    <div class="objetivo botones row m-1 justify-content-between">
        <div class="col-3 p-0 d-flex justify-content-center">
            <button class="uploadfile imagen btn btn-primary fw-bold" type="button">
                <label for="id_objetivo_imagen">
                    <i class="fa-solid fa-image"></i>
                    <span class="label d-none d-sm-inline">
                        {% if objetivo_imagen and objetivo_imagen != "" %}
                            {{ objetivo_imagen }}
                        {% else %}
                            {{ general_form.objetivo_imagen.label }}
                        {% endif %}
                    </span>
                </label>
                {{ general_form.objetivo_imagen }}
            </button>
        </div>

        <div class="col-3 p-0 d-flex justify-content-center">
            <button class="uploadfile uploadaudio btn btn-primary fw-bold"
                    type="button">
                <label for="id_objetivo_audio">
                    <i class="fa-solid fa-headphones"></i>
                    <span class="label d-none d-sm-inline">
                        {% if objetivo_audio and objetivo_audio != "" %}
                            {{ objetivo_audio }}
                        {% else %}
                            {{ general_form.objetivo_audio.label }}
                        {% endif %}
                    </span>
                </label>
                {{ general_form.objetivo_audio }}
            </button>
        </div>

        <div class="col-3 p-0 d-flex justify-content-center">
            <button class="uploadfile video btn btn-primary fw-bold" type="button">
                <label for="id_objetivo_video">
                    <i class="fa-solid fa-video"></i>
                    <span class="label d-none d-sm-inline">
                        {% if objetivo_video and objetivo_video != "" %}
                            {{ objetivo_video }}
                        {% else %}
                            {{ general_form.objetivo_video.label }}
                        {% endif %}
                    </span>
                </label>
                {{ general_form.objetivo_video }}
            </button>
        </div>
    </div>

    <div class="row align-items-center">
        <div class="col-9 col-sm-10 col-lg-11 {{ general_form.objetivo_texto.name }}">
            {{ general_form.objetivo_texto }}
        </div>
        <div class="col-2 col-lg-1 d-flex justify-content-center">
            {% include 'YoPuedo/elementos/microfono.html' with elementRecognition=general_form.objetivo_texto.id_for_label %}
        </div>
    </div>

    {% for error in general_form.objetivo_texto.errors%}
    <div class="errorlist">
      <i class="bi bi-x-circle-fill"></i>
      {{ error }}
    </div>
    {% endfor %}
</div>

<div class='form-group fw-bold {% if general_form.categoria.errors %} errorlist {% endif %} mt-4 row'>
    <div class="col-md-2 col-sm-4">
        <i class="fa-solid fa-square-check"></i>
        {{ general_form.categoria.label }}
    </div>
    {{ general_form.categoria }}

    {% for error in general_form.categoria.errors%}
    <div class="errorlist">
      <i class="bi bi-x-circle-fill"></i>
      {{ error }}
    </div>
    {% endfor %}
</div>

<div class='form-group fw-bold {% if general_form.recompensa_texto.errors %} errorlist {% endif %} mt-4'>
    <i class="fa-solid fa-trophy"></i>
    Recompensa:
    <div class="recompensa botones row m-1 justify-content-between">
        <div class="col-3 p-0 d-flex justify-content-center">
            <button class="uploadfile imagen btn btn-primary fw-bold" type="button">
                <label for="id_recompensa_imagen">
                    <i class="fa-solid fa-image"></i>
                    <span class="label d-none d-sm-inline">
                        {% if recompensa_imagen and recompensa_imagen != "" %}
                            {{ recompensa_imagen }}
                        {% else %}
                            {{ general_form.recompensa_imagen.label }}
                        {% endif %}
                    </span>
                </label>
                {{ general_form.recompensa_imagen }}
            </button>
        </div>

        <div class="col-3 p-0 d-flex justify-content-center">
            <button class="uploadfile uploadaudio btn btn-primary fw-bold" type="button">
                <label for="id_recompensa_audio">
                    <i class="fa-solid fa-headphones"></i>
                    <span class="label d-none d-sm-inline">
                        {% if recompensa_audio and recompensa_audio != "" %}
                            {{ recompensa_audio }}
                        {% else %}
                            {{ general_form.recompensa_audio.label }}
                        {% endif %}
                    </span>
                </label>
                {{ general_form.recompensa_audio }}
            </button>
        </div>

        <div class="col-3 p-0 d-flex justify-content-center">
            <button class="uploadfile video btn btn-primary fw-bold" type="button">
                <label for="id_recompensa_video">
                    <i class="fa-solid fa-video"></i>
                    <span class="label d-none d-sm-inline">
                        {% if recompensa_video and recompensa_video != "" %}
                            {{ recompensa_video }}
                        {% else %}
                            {{ general_form.recompensa_video.label }}
                        {% endif %}
                    </span>
                </label>
                {{ general_form.recompensa_video }}
            </button>
        </div>
    </div>

    <div class="row align-items-center">
        <div class="col-9 col-sm-10 col-lg-11 {{ general_form.recompensa_texto.name }}">
            {{ general_form.recompensa_texto }}
        </div>
        <div class="col-2 col-lg-1 d-flex justify-content-center">
            {% include 'YoPuedo/elementos/microfono.html' with elementRecognition=general_form.recompensa_texto.id_for_label %}
        </div>
    </div>

    {% for error in general_form.recompensa_texto.errors%}
    <div class="errorlist">
      <i class="bi bi-x-circle-fill"></i>
      {{ error }}
    </div>
    {% endfor %}
</div>

<div class="row">
    {% if "/editar_reto/" in request.path %}
    <div class="col d-flex justify-content-start mt-2 mt-sm-3 mt-lg-5">
        <button id="boton-iniciar" class="btn btn-primary fw-bold" type="button"
                onclick="iniciarReto()">
            <i class="fa-solid fa-play"></i>
            Iniciar reto
        </button>
    </div>
    {% endif %}
    <div class='col d-flex justify-content-end mt-2 mt-sm-3 mt-lg-5'>
        <button id="boton-siguiente" class="btn btn-primary fw-bold" type="button"
                onclick="cambiarPestana('etapas', 'form-reto-content')">
            Siguiente
            <i class="fa-solid fa-angle-right"></i>
        </button>
    </div>
</div>